# Generated by Django 5.0.7 on 2024-09-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_doctor', models.CharField(max_length=12, unique=True, verbose_name='RUT del Doctor')),
                ('nombre_doctor', models.CharField(max_length=100, verbose_name='Nombre del Doctor')),
                ('especialidad_doctor', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('fono_doctor', models.CharField(max_length=15, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'db_table': 'doctores',
            },
        ),
        migrations.CreateModel(
            name='nuevoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=150, verbose_name='Usuario')),
                ('contraseña', models.CharField(blank=True, max_length=150, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=35, verbose_name='Nombre Completo')),
                ('nombre_social', models.CharField(blank=True, max_length=35, verbose_name='Nombre Social')),
                ('edad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('pais_nacimiento', models.CharField(blank=True, max_length=50, verbose_name='País de Nacimiento')),
                ('nacionalidad', models.CharField(blank=True, max_length=50, verbose_name='Nacionalidad')),
                ('idioma_hablado', models.CharField(blank=True, max_length=50, verbose_name='Idioma')),
                ('metodo_contacto_fono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('metodo_contacto_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('tipo_documento_identidad', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Documento')),
                ('numero_documento_identidad', models.CharField(blank=True, max_length=25, verbose_name='Número de Documento')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'db_table': 'responsable',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=35, verbose_name='Nombre Completo')),
                ('nombre_social', models.CharField(blank=True, max_length=35, verbose_name='Nombre Social')),
                ('edad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('pais_nacimiento', models.CharField(blank=True, max_length=50, verbose_name='País de Nacimiento')),
                ('region_zona_nacimiento', models.CharField(blank=True, max_length=100, verbose_name='Región/Zona de Nacimiento')),
                ('region_zona_residencia_actual', models.CharField(blank=True, max_length=100, verbose_name='Región/Zona de Residencia Actual')),
                ('nacionalidad', models.CharField(blank=True, max_length=50, verbose_name='Nacionalidad')),
                ('idioma_hablado', models.CharField(blank=True, max_length=50, verbose_name='Idioma')),
                ('metodo_contacto_fono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('metodo_contacto_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('tipo_documento_identidad', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Documento')),
                ('numero_documento_identidad', models.CharField(blank=True, max_length=25, verbose_name='Número de Documento')),
                ('es_paciente', models.BooleanField(default=False, verbose_name='¿Es el paciente?')),
                ('relacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Relación con Responsable')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacto_hospital.responsable', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
            },
        ),
    ]
