# Generated by Django 5.0.7 on 2024-08-20 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_doctor', models.CharField(max_length=12, unique=True)),
                ('nombre_doctor', models.CharField(max_length=100)),
                ('especialidad_doctor', models.CharField(max_length=100)),
                ('fono_doctor', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'db_table': 'doctores',
            },
        ),
        migrations.CreateModel(
            name='nuevoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=150, verbose_name='Usuario')),
                ('contraseña', models.CharField(blank=True, max_length=150, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=35)),
                ('nombre_social', models.CharField(blank=True, max_length=35, null=True)),
                ('edad', models.PositiveIntegerField()),
                ('pais_nacimiento', models.CharField(max_length=50)),
                ('region_zona_nacimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('region_zona_residencia_actual', models.CharField(blank=True, max_length=100, null=True)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('idioma_hablado', models.CharField(max_length=50)),
                ('metodo_contacto_fono', models.CharField(blank=True, max_length=15, null=True)),
                ('metodo_contacto_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo_documento_identidad', models.CharField(max_length=50)),
                ('numero_documento_identidad', models.CharField(max_length=25, unique=True)),
                ('doctor_paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacto_hospital.doctores')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
            },
        ),
    ]
