# Generated by Django 5.0.7 on 2024-08-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='doctor_paciente',
        ),
    ]
