# Generated by Django 5.0.7 on 2024-08-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0002_remove_pacientes_doctor_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='numero_documento_identidad',
            field=models.CharField(max_length=25),
        ),
    ]
