# Generated by Django 5.0.7 on 2024-09-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0002_rename_edad_responsable_edad_responsable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='es_paciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='relacion',
        ),
        migrations.AddField(
            model_name='responsable',
            name='es_paciente',
            field=models.BooleanField(default=False, verbose_name='¿Es el paciente?'),
        ),
        migrations.AddField(
            model_name='responsable',
            name='relacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relación con Responsable'),
        ),
    ]
