# Generated by Django 5.0.7 on 2024-09-02 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0003_alter_pacientes_numero_documento_identidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_paciente', models.BooleanField()),
                ('relacion', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_completo_responsable', models.CharField(max_length=35)),
                ('telefono_responsable', models.CharField(max_length=15)),
                ('email_responsable', models.EmailField(max_length=254)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='contacto_hospital.pacientes')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'db_table': 'responsables',
            },
        ),
    ]
