# Generated by Django 5.0.7 on 2024-09-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0003_remove_paciente_es_paciente_remove_paciente_relacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergias_farmacos',
            field=models.ManyToManyField(blank=True, related_name='alergias_farmacos', to='contacto_hospital.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias_no_farmacos',
            field=models.ManyToManyField(blank=True, related_name='alergias_no_farmacos', to='contacto_hospital.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cirugias_comunes',
            field=models.ManyToManyField(blank=True, related_name='cirugias_comunes', to='contacto_hospital.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cirugias_traumatologicas',
            field=models.ManyToManyField(blank=True, related_name='cirugias_traumatologicas', to='contacto_hospital.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='detalle_alergias_farmacos',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='detalle_alergias_no_farmacos',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='detalle_farmacos_cronicos',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='detalle_farmacos_no_cronicos',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedades_comunes',
            field=models.ManyToManyField(blank=True, related_name='enfermedades_comunes', to='contacto_hospital.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedades_cronicas',
            field=models.ManyToManyField(blank=True, related_name='enfermedades_cronicas', to='contacto_hospital.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='farmacos_cronicos',
            field=models.ManyToManyField(blank=True, related_name='farmacos_cronicos', to='contacto_hospital.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='farmacos_no_cronicos',
            field=models.ManyToManyField(blank=True, related_name='farmacos_no_cronicos', to='contacto_hospital.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='otras_cirugias_comunes',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='otras_cirugias_traumatologicas',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='otras_enfermedades_comunes',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='otras_enfermedades_cronicas',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='otros_alergias_farmacos',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='otros_alergias_no_farmacos',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='otros_antecedentes',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='otros_farmacos_cronicos',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='otros_farmacos_no_cronicos',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
