# Generated by Django 5.0.7 on 2024-09-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0004_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsable',
            name='email_responsable',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='telefono_responsable',
        ),
        migrations.AddField(
            model_name='responsable',
            name='edad_responsable',
            field=models.PositiveBigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsable',
            name='idioma_responsable',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsable',
            name='metodo_contacto_email_responsable',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='responsable',
            name='metodo_contacto_fono_responsable',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='responsable',
            name='nacionalidad_responsable',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsable',
            name='nombre_social_responsable',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='responsable',
            name='numero_documento_identidad_responsable',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsable',
            name='pais_nacimiento_responsable',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsable',
            name='tipo_documento_identidad_responsable',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
