# Generated by Django 5.0.7 on 2024-09-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0005_remove_responsable_email_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='edad_responsable',
            field=models.PositiveBigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='es_paciente',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='idioma_responsable',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='metodo_contacto_email_responsable',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='metodo_contacto_fono_responsable',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='nacionalidad_responsable',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='nombre_completo_responsable',
            field=models.CharField(default=None, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='nombre_social_responsable',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='numero_documento_identidad_responsable',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='pais_nacimiento_responsable',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='relacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='tipo_documento_identidad_responsable',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Responsable',
        ),
    ]
