# Generated by Django 5.0.7 on 2024-09-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0006_pacientes_edad_responsable_pacientes_es_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='nombre_completo_responsable',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
