# Generated by Django 5.0.7 on 2024-09-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0006_remove_paciente_alergias_no_farmacos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='condiciones_cronicas',
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedades_cronicas',
            field=models.TextField(blank=True, help_text="Seleccione las enfermedades crónicas y especifique otras si selecciona 'Otro'."),
        ),
        migrations.AddField(
            model_name='paciente',
            name='otras_alergias_comunes',
            field=models.CharField(blank=True, help_text='Otras alergias comunes (25 caracteres máx.)', max_length=25),
        ),
        migrations.AddField(
            model_name='paciente',
            name='otras_alergias_farmacos',
            field=models.CharField(blank=True, help_text='Otras alergias a fármacos (25 caracteres máx.)', max_length=25),
        ),
        migrations.AddField(
            model_name='paciente',
            name='otros_farmacos_patologias_cronicas',
            field=models.CharField(blank=True, help_text='Otros fármacos utilizados para patologías crónicas (25 caracteres máx.)', max_length=25),
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='alergias_comunes',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='alergias_farmacos',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cirugias_comunes',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cirugias_traumatologicas',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='enfermedades_comunes',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='farmacos_no_cronicos',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='farmacos_patologias_cronicas',
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias_comunes',
            field=models.TextField(blank=True, help_text="Seleccione las alergias más comunes y especifique otras si selecciona 'Otro'."),
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias_farmacos',
            field=models.TextField(blank=True, help_text="Seleccione las alergias a fármacos más comunes y especifique otras si selecciona 'NINGUNA'."),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cirugias_comunes',
            field=models.TextField(blank=True, help_text="Seleccione las cirugías comunes y especifique otras si selecciona 'Otro'."),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cirugias_traumatologicas',
            field=models.TextField(blank=True, help_text="Seleccione las cirugías traumatológicas y especifique otras si selecciona 'Otro'."),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedades_comunes',
            field=models.TextField(blank=True, help_text="Seleccione las enfermedades comunes y especifique otras si selecciona 'Otro'."),
        ),
        migrations.AddField(
            model_name='paciente',
            name='farmacos_no_cronicos',
            field=models.TextField(blank=True, help_text="Seleccione los fármacos más usados en Chile (no crónicos) y especifique otros si selecciona 'NINGUNA'."),
        ),
        migrations.AddField(
            model_name='paciente',
            name='farmacos_patologias_cronicas',
            field=models.TextField(blank=True, help_text="Seleccione los fármacos utilizados para patologías crónicas y especifique otros si selecciona 'Otro'."),
        ),
    ]
