# Generated by Django 5.0.7 on 2024-09-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0007_remove_paciente_condiciones_cronicas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='otros_alergias_farmacos',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='otros_alergias_no_farmacos',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='otros_farmacos_cronicos',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='otras_cirugias_comunes',
            field=models.CharField(blank=True, default=None, help_text='Otras cirugías comunes (25 caracteres máx.)', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='otras_cirugias_traumatologicas',
            field=models.CharField(blank=True, default=None, help_text='Otras cirugías traumatológicas (25 caracteres máx.)', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='otras_enfermedades_comunes',
            field=models.CharField(blank=True, default=None, help_text='Otras enfermedades comunes (25 caracteres máx.)', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='otras_enfermedades_cronicas',
            field=models.CharField(blank=True, default=None, help_text='Otras enfermedades crónicas (25 caracteres máx.)', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='otros_farmacos_no_cronicos',
            field=models.CharField(blank=True, default=None, help_text='Otros fármacos (25 caracteres máx.)', max_length=25),
            preserve_default=False,
        ),
    ]
