# Generated by Django 5.0.7 on 2024-09-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0008_alter_pacientes_edad_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='edad_responsable',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='idioma_responsable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='nacionalidad_responsable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='nombre_completo_responsable',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='numero_documento_identidad_responsable',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='pais_nacimiento_responsable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='tipo_documento_identidad_responsable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
