# Generated by Django 5.0.7 on 2024-09-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0008_remove_paciente_otros_alergias_farmacos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='alergias_farmacos',
            field=models.TextField(blank=True, help_text="Seleccione las alergias a fármacos más comunes y especifique otras si selecciona 'Otro'."),
        ),
    ]
