# Generated by Django 5.0.7 on 2024-09-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0009_alter_paciente_alergias_farmacos'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='centro_salud_previo',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No'), ('Otro', 'Otro')], default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='experimentado_problema_anteriormente',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default=None, help_text='Seleccione si ha experimentado este problema anteriormente.', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='frecuencia_otros',
            field=models.CharField(blank=True, help_text="Especifique la frecuencia si selecciona 'Otros'.", max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='frecuencia_problema',
            field=models.CharField(choices=[('Diaria', 'Diaria'), ('Semanal', 'Semanal'), ('Mensual', 'Mensual'), ('Anual', 'Anual'), ('Otros', 'Otros')], default=None, help_text='Seleccione con qué frecuencia ha experimentado este problema.', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='motivo_consulta',
            field=models.TextField(blank=True, help_text='Seleccione uno o varios motivos de consulta.'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='motivo_consulta_texto',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='otro_centro_salud',
            field=models.CharField(blank=True, help_text='Especifique otro centro de salud (25 caracteres máx.)', max_length=25),
        ),
        migrations.AddField(
            model_name='paciente',
            name='otro_resolucion_salud',
            field=models.CharField(blank=True, help_text='Especifique otro (25 caracteres máx.)', max_length=25),
        ),
        migrations.AddField(
            model_name='paciente',
            name='otros_motivos',
            field=models.CharField(blank=True, help_text='Especifique otros motivos (50 caracteres máx.).', max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='resolucion_problema_salud',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No'), ('Parcialmente', 'Parcialmente'), ('Otro', 'Otro')], default=None, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='tiempo_sintomas',
            field=models.CharField(choices=[('Minutos', 'Minutos'), ('Horas', 'Horas'), ('Días', 'Días'), ('Semanas', 'Semanas'), ('Meses', 'Meses'), ('Años', 'Años')], default=None, help_text='Seleccione aproximadamente hace cuánto comenzaron los síntomas.', max_length=20),
            preserve_default=False,
        ),
    ]
