# Generated by Django 5.0.7 on 2024-09-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0009_alter_pacientes_edad_responsable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='es_paciente',
            field=models.BooleanField(default=False),
        ),
    ]
