# Generated by Django 5.0.7 on 2024-09-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0010_paciente_centro_salud_previo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='nombre',
        ),
    ]
