# Generated by Django 5.0.7 on 2024-09-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0011_alter_pacientes_es_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='es_paciente',
            field=models.BooleanField(null=True),
        ),
    ]
