# Generated by Django 5.0.7 on 2024-09-16 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0011_remove_paciente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(default=None, help_text='Ingrese su correo electrónico', max_length=254, verbose_name='Correo Electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_envio',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 9, 16, 19, 44, 32, 298301, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Envío'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='hora_envio',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 16, 19, 44, 36, 481109, tzinfo=datetime.timezone.utc), verbose_name='Hora de Envío'),
            preserve_default=False,
        ),
    ]
