# Generated by Django 5.0.7 on 2024-09-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0012_paciente_email_paciente_fecha_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='autorizacion_informacion',
            field=models.CharField(choices=[('aceptar', 'Acepto'), ('rechazar', 'Rechazo')], default='rechazar', max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='consentimiento_procedimientos',
            field=models.CharField(choices=[('aceptar', 'Acepto'), ('rechazar', 'Rechazo')], default='rechazar', max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='descargo_responsabilidad',
            field=models.CharField(choices=[('aceptar', 'Acepto'), ('rechazar', 'Rechazo')], default='rechazar', max_length=10),
        ),
    ]
