# Generated by Django 5.0.7 on 2024-09-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0014_alter_pacientes_es_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='nombre_completo',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
