# Generated by Django 5.0.7 on 2024-09-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0015_alter_pacientes_nombre_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='edad',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='pais_nacimiento',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
