# Generated by Django 5.0.7 on 2024-09-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0016_alter_pacientes_edad_alter_pacientes_pais_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='es_paciente',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='idioma_hablado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='numero_documento_identidad',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='pais_nacimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='tipo_documento_identidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
