# Generated by Django 5.0.7 on 2024-09-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0017_alter_paciente_autorizacion_informacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='entendimiento_enfermedad',
            field=models.CharField(choices=[('Sí, por completo', 'Sí, por completo'), ('Solo parcialmente', 'Solo parcialmente'), ('Entiendo algunas de mis enfermedades, otras no', 'Entiendo algunas de mis enfermedades, otras no'), ('No, nada', 'No, nada')], default=None, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='expectativas',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='preguntas',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
    ]
