# Generated by Django 5.0.7 on 2024-09-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0017_alter_pacientes_edad_alter_pacientes_es_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='es_paciente',
            field=models.BooleanField(default=False),
        ),
    ]
