# Generated by Django 5.0.7 on 2024-09-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_hospital', '0018_paciente_entendimiento_enfermedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='entendimiento_enfermedad',
            field=models.CharField(choices=[('Sí, por completo', 'Sí, por completo'), ('Solo parcialmente', 'Solo parcialmente'), ('Entiendo algunas de mis enfermedades, otras no', 'Entiendo algunas de mis enfermedades, otras no'), ('No, nada', 'No, nada')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='expectativas',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='preguntas',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
